<?php

namespace ContainerI3Z0Yrw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MaFA1RXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.maFA1RX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.maFA1RX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'dkRepository' => ['privates', 'App\\Repository\\DigitalKnowledgeRepository', 'getDigitalKnowledgeRepositoryService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'm1Repository' => ['privates', 'App\\Repository\\Mobbning1Repository', 'getMobbning1RepositoryService', true],
            'm2Repository' => ['privates', 'App\\Repository\\Mobbning2Repository', 'getMobbning2RepositoryService', true],
        ], [
            'dkRepository' => 'App\\Repository\\DigitalKnowledgeRepository',
            'doctrine' => '?',
            'm1Repository' => 'App\\Repository\\Mobbning1Repository',
            'm2Repository' => 'App\\Repository\\Mobbning2Repository',
        ]);
    }
}
