<?php

namespace ContainerI3Z0Yrw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TwrH7ZBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TwrH7ZB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TwrH7ZB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'chartBuilder' => ['privates', 'chartjs.builder', 'getChartjs_BuilderService', true],
            'dKRepository' => ['privates', 'App\\Repository\\DigitalKnowledgeRepository', 'getDigitalKnowledgeRepositoryService', true],
            'm1Repository' => ['privates', 'App\\Repository\\Mobbning1Repository', 'getMobbning1RepositoryService', true],
            'm2Repository' => ['privates', 'App\\Repository\\Mobbning2Repository', 'getMobbning2RepositoryService', true],
        ], [
            'chartBuilder' => '?',
            'dKRepository' => 'App\\Repository\\DigitalKnowledgeRepository',
            'm1Repository' => 'App\\Repository\\Mobbning1Repository',
            'm2Repository' => 'App\\Repository\\Mobbning2Repository',
        ]);
    }
}
