<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI3Z0Yrw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI3Z0Yrw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI3Z0Yrw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI3Z0Yrw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerI3Z0Yrw\App_KernelDevDebugContainer([
    'container.build_hash' => 'I3Z0Yrw',
    'container.build_id' => '59c92046',
    'container.build_time' => 1653461509,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI3Z0Yrw');
